In [7]:
import pandas as pd
data = pd.read_csv("Data UTS Kecerdasan Bisnis (20-150 dan 20-162).csv")
# df = pd.DataFrame(data)
# df
data

,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,Tidak,16.60,Ya,Tidak,Tidak,3.0,30.0,Tidak,Perempuan,Ya,Ya,Sangat Baik,Ya,Tidak,Ya
1,Tidak,20.34,Tidak,Tidak,Ya,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
2,Tidak,26.58,Ya,Tidak,Tidak,20.0,30.0,Tidak,Laki - Laki,Ya,Ya,Baik,Ya,Tidak,Tidak
3,Tidak,24.21,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Ya
4,Tidak,23.71,Tidak,Tidak,Tidak,28.0,0.0,Ya,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Ya,27.41,Ya,Tidak,Tidak,7.0,0.0,Ya,Laki - Laki,Ya,Tidak,Baik,Ya,Tidak,Tidak
319791,Tidak,29.84,Ya,Tidak,Tidak,0.0,0.0,Tidak,Laki - Laki,Tidak,Ya,Sangat Baik,Ya,Tidak,Tidak
319792,Tidak,24.24,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak
319793,Tidak,32.81,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Tidak
319794,Tidak,46.56,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak

In [23]:
data.to_csv("Data UTS Kecerdasan Bisnis (20-150 dan 20-162).csv", sep=',')

In [24]:
import pandas as pd
data = pd.read_csv("Data UTS Kecerdasan Bisnis (20-150 dan 20-162).csv")
# df = pd.DataFrame(data)
# df
data

,Unnamed: 0.1,Unnamed: 0,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,0,0,Tidak,16.60,Ya,Tidak,Tidak,3.0,30.0,Tidak,Perempuan,Ya,Ya,Sangat Baik,Ya,Tidak,Ya
1,1,1,Tidak,20.34,Tidak,Tidak,Ya,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
2,2,2,Tidak,26.58,Ya,Tidak,Tidak,20.0,30.0,Tidak,Laki - Laki,Ya,Ya,Baik,Ya,Tidak,Tidak
3,3,3,Tidak,24.21,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Ya
4,4,4,Tidak,23.71,Tidak,Tidak,Tidak,28.0,0.0,Ya,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,319790,319790,Ya,27.41,Ya,Tidak,Tidak,7.0,0.0,Ya,Laki - Laki,Ya,Tidak,Baik,Ya,Tidak,Tidak
319791,319791,319791,Tidak,29.84,Ya,Tidak,Tidak,0.0,0.0,Tidak,Laki - Laki,Tidak,Ya,Sangat Baik,Ya,Tidak,Tidak
319792,319792,319792,Tidak,24.24,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak
319793,319793,319793,Tidak,32.81,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Tidak
319794,319794,319794,Tidak,46.56,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak

In [31]:
# col = ["Unnamed: 0.1","Unnamed: 0"]
# drop(columns=col)

,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,Tidak,16.60,Ya,Tidak,Tidak,3.0,30.0,Tidak,Perempuan,Ya,Ya,Sangat Baik,Ya,Tidak,Ya
1,Tidak,20.34,Tidak,Tidak,Ya,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
2,Tidak,26.58,Ya,Tidak,Tidak,20.0,30.0,Tidak,Laki - Laki,Ya,Ya,Baik,Ya,Tidak,Tidak
3,Tidak,24.21,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Ya
4,Tidak,23.71,Tidak,Tidak,Tidak,28.0,0.0,Ya,Perempuan,Tidak,Ya,Sangat Baik,Tidak,Tidak,Tidak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Ya,27.41,Ya,Tidak,Tidak,7.0,0.0,Ya,Laki - Laki,Ya,Tidak,Baik,Ya,Tidak,Tidak
319791,Tidak,29.84,Ya,Tidak,Tidak,0.0,0.0,Tidak,Laki - Laki,Tidak,Ya,Sangat Baik,Ya,Tidak,Tidak
319792,Tidak,24.24,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak
319793,Tidak,32.81,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Tidak,Cukup,Tidak,Tidak,Tidak
319794,Tidak,46.56,Tidak,Tidak,Tidak,0.0,0.0,Tidak,Perempuan,Tidak,Ya,Cukup,Tidak,Tidak,Tidak

In [32]:
df = pd.DataFrame(data)


# Langkah 2: Mengonversi Semua Kolom Menjadi Kategori dan Kemudian Menjadi Kode Kategori
df = df.apply(lambda x: pd.Categorical(x).codes)
print("\nDataFrame setelah mengubah semua kolom menjadi kode kategori:")
df

DataFrame setelah mengubah semua kolom menjadi kode kategori:

,Unnamed: 0.1,Unnamed: 0,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,0,0,0,223,1,0,0,3,30,0,1,1,1,4,1,0,1
1,1,1,0,524,0,0,1,0,0,0,1,0,1,4,0,0,0
2,2,2,0,1103,1,0,0,20,30,0,0,1,1,1,1,0,0
3,3,3,0,883,0,0,0,0,0,0,1,0,0,2,0,0,1
4,4,4,0,837,0,0,0,28,0,1,1,0,1,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,319790,319790,1,1180,1,0,0,7,0,1,0,1,0,1,1,0,0
319791,319791,319791,0,1397,1,0,0,0,0,0,0,0,1,4,1,0,0
319792,319792,319792,0,886,0,0,0,0,0,0,1,0,1,2,0,0,0
319793,319793,319793,0,1658,0,0,0,0,0,0,1,0,0,2,0,0,0
319794,319794,319794,0,2700,0,0,0,0,0,0,1,0,1,2,0,0,0

In [33]:
col = ["Unnamed: 0.1","Unnamed: 0"]
df.drop(columns=col)

,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,0,223,1,0,0,3,30,0,1,1,1,4,1,0,1
1,0,524,0,0,1,0,0,0,1,0,1,4,0,0,0
2,0,1103,1,0,0,20,30,0,0,1,1,1,1,0,0
3,0,883,0,0,0,0,0,0,1,0,0,2,0,0,1
4,0,837,0,0,0,28,0,1,1,0,1,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,1180,1,0,0,7,0,1,0,1,0,1,1,0,0
319791,0,1397,1,0,0,0,0,0,0,0,1,4,1,0,0
319792,0,886,0,0,0,0,0,0,1,0,1,2,0,0,0
319793,0,1658,0,0,0,0,0,0,1,0,0,2,0,0,0
319794,0,2700,0,0,0,0,0,0,1,0,1,2,0,0,0

In [35]:
df

,Unnamed: 0.1,Unnamed: 0,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,0,0,0,223,1,0,0,3,30,0,1,1,1,4,1,0,1
1,1,1,0,524,0,0,1,0,0,0,1,0,1,4,0,0,0
2,2,2,0,1103,1,0,0,20,30,0,0,1,1,1,1,0,0
3,3,3,0,883,0,0,0,0,0,0,1,0,0,2,0,0,1
4,4,4,0,837,0,0,0,28,0,1,1,0,1,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,319790,319790,1,1180,1,0,0,7,0,1,0,1,0,1,1,0,0
319791,319791,319791,0,1397,1,0,0,0,0,0,0,0,1,4,1,0,0
319792,319792,319792,0,886,0,0,0,0,0,0,1,0,1,2,0,0,0
319793,319793,319793,0,1658,0,0,0,0,0,0,1,0,0,2,0,0,0
319794,319794,319794,0,2700,0,0,0,0,0,0,1,0,1,2,0,0,0

In [37]:
df.to_csv('data_fix.csv')
df.astype

<bound method NDFrame.astype of         Unnamed: 0.1  Unnamed: 0  Penyakit Jantung   BMI  Perokok Aktif  \
0                  0           0                 0   223              1
1                  1           1                 0   524              0
2                  2           2                 0  1103              1
3                  3           3                 0   883              0
4                  4           4                 0   837              0
...              ...         ...               ...   ...            ...
319790        319790      319790                 1  1180              1
319791        319791      319791                 0  1397              1
319792        319792      319792                 0   886              0
319793        319793      319793                 0  1658              0
319794        319794      319794                 0  2700              0

        Peminum Alkohol  Stroke  Kesehatan Fisik  Kesehatan Mental  \
0                     0       0                3                30
1                     0       1                0                 0
2                     0       0               20                30
3                     0       0                0                 0
4                     0       0               28                 0
...                 ...     ...              ...               ...
319790                0       0                7                 0
319791                0       0                0                 0
319792                0       0                0                 0
319793                0       0                0                 0
319794                0       0                0                 0

        DiffWalking  Jenis Kelamin  Penderita Diabetes  Aktivitas Fisik  \
0                 0              1                   1                1
1                 0              1                   0                1
2                 0              0                   1                1
3                 0              1                   0                0
4                 1              1                   0                1
...             ...            ...                 ...              ...
319790            1              0                   1                0
319791            0              0                   0                1
319792            0              1                   0                1
319793            0              1                   0                0
319794            0              1                   0                1

        Kesehatan Gen  Asma  Penyakit Ginjal  Kanker Kulit
0                   4     1                0             1
1                   4     0                0             0
2                   1     1                0             0
3                   2     0                0             1
4                   4     0                0             0
...               ...   ...              ...           ...
319790              1     1                0             0
319791              4     1                0             0
319792              2     0                0             0
319793              2     0                0             0
319794              2     0                0             0

[319795 rows x 17 columns]>

In [38]:
df

,Unnamed: 0.1,Unnamed: 0,Penyakit Jantung,BMI,Perokok Aktif,Peminum Alkohol,Stroke,Kesehatan Fisik,Kesehatan Mental,DiffWalking,Jenis Kelamin,Penderita Diabetes,Aktivitas Fisik,Kesehatan Gen,Asma,Penyakit Ginjal,Kanker Kulit
0,0,0,0,223,1,0,0,3,30,0,1,1,1,4,1,0,1
1,1,1,0,524,0,0,1,0,0,0,1,0,1,4,0,0,0
2,2,2,0,1103,1,0,0,20,30,0,0,1,1,1,1,0,0
3,3,3,0,883,0,0,0,0,0,0,1,0,0,2,0,0,1
4,4,4,0,837,0,0,0,28,0,1,1,0,1,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,319790,319790,1,1180,1,0,0,7,0,1,0,1,0,1,1,0,0
319791,319791,319791,0,1397,1,0,0,0,0,0,0,0,1,4,1,0,0
319792,319792,319792,0,886,0,0,0,0,0,0,1,0,1,2,0,0,0
319793,319793,319793,0,1658,0,0,0,0,0,0,1,0,0,2,0,0,0
319794,319794,319794,0,2700,0,0,0,0,0,0,1,0,1,2,0,0,0